package ctag.domain.model.processvigilanceversionparameter;


public interface ProcessVigilanceVersionParameterFactory extends GenericFactory<ProcessVigilanceVersionParameter> {
  
 ProcessVigilanceVersionParameter createProcessVigilanceVersionParameter(Integer idProcessVigilanceVersion,Integer idParameter,Integer point,float nominal,boolean booleanNominal,Integer idProcessVigilanceVersion,Integer idParameter);

 ProcessVigilanceVersionParameter createProcessVigilanceVersionParameter(Integer ProcessVigilanceVersionParameterId, Integer idProcessVigilanceVersion,Integer idParameter,Integer point,float nominal,boolean booleanNominal,Integer idProcessVigilanceVersion,Integer idParameter);


}
